# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='mechanics',
            field=models.ManyToManyField(blank=True, to='boardgames.GameMechanic'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rating_bayes_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='playersuggestion',
            name='best',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersuggestion',
            name='not_recommended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersuggestion',
            name='recommended',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
