# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_auto_20170129_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersuggestion',
            name='board_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_suggestions', to='boardgames.BoardGame'),
        ),
    ]
