# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0003_auto_20170131_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='year',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
