# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0006_auto_20170131_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
