# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0007_auto_20170131_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='expansion',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
