# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('bgg_username', models.CharField(max_length=100)),
                ('board_games', models.ManyToManyField(related_name='owned_by', to='boardgames.BoardGame')),
                ('groups', models.ManyToManyField(related_name='members', to='players.GameGroup')),
            ],
        ),
    ]
